wandb: {}
project_name: whu
restore_ckpt: "./checkpoints/mix_all.pth"
# restore_ckpt: "/data2/cjd/mono_fusion/checkpoints/sceneflow.pth"
logdir: './checkpoints/whu/'
encoder: 'vitl'
batch_size: 8
train_datasets: ['whu']
lr: 1e-4
wdecay: 1e-5
total_step: 50000
save_frequency: 2000
save_path: ./checkpoints/whu/
val_frequency: 2000
image_size: [1024, 1024]
train_iters: 22
valid_iters: 32
val_dataset: 'whu'
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 375
saturation_range: [0.7, 1.3]
do_flip: False
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 4
seed: 666