tensorboard: {}
project_name: monster-stereo-training-aug-mix-all-no-quantile
project_dir: ./logs/us3d/
restore_ckpt: ./checkpoints/us3d/11220.pth
encoder: 'vitl'
batch_size: 8
train_datasets: ['us3d']
train_split_ratio: 0.7
val_split_ratio: 0.15
lr: 3e-5
wdecay: 1e-5
current_step: 11220
total_step: 26180
train_image_frequency: 25
val_image_frequency: 25
save_frequency: 3750
save_path: ./checkpoints/us3d/
val_frequency: 375
image_size: [512, 1024]
train_iters: 24
valid_iters: 24
corr_implementation: "reg"
corr_levels: 2
corr_radius: 4
n_downsample: 2
n_gru_layers: 3
hidden_dims: [128, 128, 128]
max_disp: 128
saturation_range: [0.9, 1.1]
do_flip: 'hf'
spatial_scale: [-0.2, 0.5]
noyjitter: True
num_gpu: 8
seed: 999